DROP TABLE IF EXISTS score;
DROP TABLE IF EXISTS bet;
DROP TABLE IF EXISTS auth_tokens;
DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS match;
DROP TABLE IF EXISTS game_codes;
DROP TABLE IF EXISTS game;