name: Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "deploy" to confirm deployment'
        required: true
        type: string

jobs:
  deploy:
    if: github.event.inputs.confirm == 'deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Pulumi
        uses: pulumi/setup-pulumi@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_DEV }}
          service_account_key: ${{ secrets.GCP_SA_KEY_DEV }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID_DEV }}/server-dev:latest ./server
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID_DEV }}/server-dev:latest

      - name: Deploy to Cloud Run
        working-directory: ./infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID_DEV }}
          GCP_REGION: ${{ secrets.GCP_REGION }}
        run: |
          pulumi stack select dev
          pulumi up --yes 